#!/bin/bash
# Example: Preload multiple workflows from workflows.json

echo "🚀 Multiple Workflows Preloading Example"
echo "========================================"
echo ""

echo "📋 Setup Method 1: Auto-detection (Recommended)"
echo "----------------------------------------------"
echo ""
echo "1. Create or copy workflows.json:"
echo "   cp workflows.json.example workflows.json"
echo ""
echo "2. Edit workflows.json with your workflows"
echo ""
echo "3. During setup(), the system will automatically:"
echo "   - Detect workflows.json in root directory"
echo "   - Extract weights from all workflows"
echo "   - Deduplicate across workflows"
echo "   - Download unique weights"
echo ""
echo "No environment variables needed!"
echo ""

echo "📋 Setup Method 2: Environment Variable"
echo "--------------------------------------"
echo ""
echo "export PRELOAD_WORKFLOWS='workflows.json'"
echo "# or from remote URL:"
echo "export PRELOAD_WORKFLOWS='https://example.com/workflows.json'"
echo ""

echo "📋 Setup Method 3: In cog.yaml"
echo "-----------------------------"
echo ""
echo "build:"
echo "  python_version: \"3.11\""
echo "  run:"
echo "    - cp workflows.json.example workflows.json"
echo ""

echo "📊 Example workflows.json Structure"
echo "---------------------------------"
echo ""
echo "Named workflows (recommended):"
echo "{"
echo "  \"flux_schnell\": {"
echo "    \"1\": {\"inputs\": {\"ckpt_name\": \"flux1-schnell.safetensors\"}, ...},"
echo "    \"2\": {\"inputs\": {\"clip_name\": \"clip_l.safetensors\"}, ...}"
echo "  },"
echo "  \"sdxl\": {"
echo "    \"1\": {\"inputs\": {\"ckpt_name\": \"sd_xl_base_1.0.safetensors\"}, ...}"
echo "  }"
echo "}"
echo ""

echo "📈 Expected Behavior"
echo "-------------------"
echo ""
echo "During setup():"
echo "  ⏳ Preloading weights from all workflows..."
echo "  📄 flux_schnell: 5 weight(s)"
echo "  📄 sdxl: 2 weight(s)"
echo ""
echo "  Found 6 unique weight(s) across 2 workflow(s)"
echo "  ⏳ Downloading 6 weight(s)..."
echo "  [1/6] flux1-schnell.safetensors... ✅"
echo "  [2/6] flux1-dev.safetensors... ✅"
echo "  [3/6] clip_l.safetensors... ✅"
echo "  [4/6] ae.safetensors... ✅"
echo "  [5/6] sd_xl_base_1.0.safetensors... ✅"
echo "  [6/6] sd_xl_refiner_1.0.safetensors... ✅"
echo ""
echo "  ✅ All workflows preloaded"
echo ""

echo "💡 Key Features"
echo "--------------"
echo "✅ Auto-detection of workflows.json"
echo "✅ Support for multiple workflows in one file"
echo "✅ Automatic weight deduplication"
echo "✅ Clear progress reporting"
echo "✅ Error handling and recovery"
echo ""

echo "📚 Documentation"
echo "---------------"
echo "See MULTIPLE_WORKFLOWS.md for:"
echo "  - Detailed format specifications"
echo "  - Advanced usage patterns"
echo "  - Troubleshooting guide"
echo "  - Performance optimization tips"
echo ""

echo "✅ Example complete!"
